name: Test Changes
run-name: ${{ github.actor }} is testing the project on ${{ github.server_url }}

on:
  issue_comment:
    types:
      - created

jobs:
  build-and-run:
    runs-on: hpc-runner
    if: |
      github.repository == 'vanderwb/test-actions'              &&
      github.event.issue.pull_request                           &&
      contains(github.event.comment.body, '/run-pr-tests')      &&
      (github.event.comment.author_association == 'OWNER'       ||
      github.event.comment.author_association == 'COLLABORATOR')

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run make
        run: make
      - name: Run test
        run: make check
      - name: Run clean
        run: make clean
      - run: echo "This job's status is ${{ job.status }}."
