name: Test Changes
run-name: ${{ github.actor }} is testing the project on ${{ github.server_url }}

on:
  push

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - run: echo "The pusher is a ${{ github.event.comment.author_association }}."
